def ft(text):
	keyword_dict = {
		'personal':['personal'],
		'professional':['professional'],
		'medical':['medical'],
		'first_name':['first name'],
		'last_name':['last name'],
		'full_name' : ['full name','complete name'],
		'gender' : ['gender','sex'],
		'age':['age'],
		'job_position':['job position','role','designation'],
		'vehicle_reg_no':['vehicle registration number','vehicle reg no','vehicle reg num'],
		'veteran_status':['veteran status'],
		'video_footage':['video','video footage'],
		'voice_recording':['voice recording'],
		'voter_registration_records':['voter registration records'],
		'weight':['weight'],
		'work_details' :['work address','work email','work email address','work phone','work phone number'],
		'arrest_records':['arrest records','criminal history'],
		'biometric_identifiers':['biometric identifiers'],
		'criminal_offenses_and_convictions':['criminal offenses','convictions'],
		'family_health_history':['family health history'],
		'fingerprints':['fingerprints'],
		'genetic_info':['genetic information'],
		'medical_records':['medical records'],
		'physical_or_mental_disability':['physical disability','mental disability'],
		'political_affiliations_and_opinions':['political affiliations','political party affiliation','political opinions'],
		'prescriptions':['prescription'],
		'religious_and_philosophical_belief':['religious belief','religion','philosophy'],
		'retina_scan':['retina scan'],
		'sexual_orientation':['sexual_orientation'],
		'sexual_partners':['sexual partners'],
		'signature':['signature'],
		'social_security':['social security','social insurance number'],
		'trade_union_membership':['trade union membership'],
		'voice_signature':['voice signature']

	}
